ATTR_SMART_DEVICE_STATUS_VALUE = "SMART_DEVICE_STATUS_VALUE"
ATTR_JSON_MOBILE_STATUS_VALUE = "MOBILE_STATUS"

ATTR_ID_DEVICE = "ID_DEVICE"
ATTR_RELAY_STATUS_VALUE = "RELAY_STATUS_VALUE"

ATTR_ID_SMART_DEVICE = "idSmartDevice"
ATTR_ID_ROOM = "idRoom"
ATTR_NAME_SMART_DEVICE = "nameSmartDevice"

ATTR_ID_TIMER = "idTimer"
ATTR_STATE_ELECTRIC = "stateElectric"
ATTR_STATE_RELAY = "stateRelay"
ATTR_IP = "ip"
ATTR_PORT = "port"

ATTR_ID_TIMER = "idTimer"
ATTR_SEC_SD = "secSD"
ATTR_MIN_SD = "minSD"
ATTR_HOUR_SD = "hourSD"
ATTR_DAY_SD = "daySD"
ATTR_MONTH_SD = "monthSD"
ATTR_YEAR_SD = "yearSD"

ATTR_ID_TIMER = "idTimer"
ATTR_STATE_ELECTRIC = "stateElectric"
ATTR_STATE_RELAY = "stateRelay"

ATTR_SENDER = "sender"
ATTR_TIMER = "timer"
ATTR_DATA = "data"

ATTR_DEVICE = "device"
ATTR_DEVICE_TIMER = "deviceTimer"

ATTR_MESSAGE_TYPE = "MESSAGE_TYPE"

ATTR_ACTIVE_VALUE = 1
ATTR_UNACTIVE_VALUE = 0
ATTR_SD001_VALUE = "SD001"
ATTR_SD002_VALUE = "SD002"
ATTR_HOST_LIGHT_VALUE = "192.168.0.106"
ATTR_HOST_PLUS_VALUE = "192.168.0.103"