ATTR_SMART_DEVICE_STATUS_VALUE = "SMART_DEVICE_STATUS_VALUE"
ATTR_ANDROID_CONTROL_STATUS_DEVICE = "ANDROID_CONTROL_STATUS_DEVICE"

ATTR_ID_SMART_DEVICE = "idSmartDevice"
ATTR_ID_ROOM = "idRoom"
ATTR_NAME_SMART_DEVICE = "nameSmartDevice"

ATTR_ID_TIMER = "idTimer"
ATTR_STATE_ELECTRIC = "stateElectric"
ATTR_STATE_RELAY = "stateRelay"
ATTR_IP = "ip"
ATTR_PORT = "port"

ATTR_ID_TIMER = "idTimer"
ATTR_SEC_SD = "secSD"
ATTR_MIN_SD = "minSD"
ATTR_HOUR_SD = "hourSD"
ATTR_DAY_SD = "daySD"
ATTR_MONTH_SD = "monthSD"
ATTR_YEAR_SD = "yearSD"

ATTR_ID_TIMER = "idTimer"
ATTR_STATE_ELECTRIC = "stateElectric"
ATTR_STATE_RELAY = "stateRelay"

ATTR_SENDER = "sender"
ATTR_TIMER = "timer"
ATTR_DATA = "data"

ATTR_DEVICE = "device"
ATTR_DEVICE_TIMER = "deviceTimer"