#-----------------------------------------------------------------------------
# Makefile - src/app/utils/jsonHelper/cWrapper/jsonBuilderWrapper
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
APP = unittest
TEST_OBJECT = src/app/utils/jsonHelper/cWrapper/jsonBuilderWrapper/jsonBuilderWrapper_smart_device_status_value


#-----------------------------------------------------------------------------
include ../Makefile

#-----------------------------------------------------------------------------