#-----------------------------------------------------------------------------
# Makefile - src/app/utils/jsonHelper/cWrapper/jsonCommonWrapper
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
APP = unittest
TEST_OBJECT = src/app/utils/jsonHelper/cWrapper/jsonCommonWrapper

#-----------------------------------------------------------------------------
LIBDIRS_jsonCommon  += $(LIDT_ROOT)/src/app/utils/jsonHelper/
LIBRARY             += jsonCommon_smart_device_status_value

#-----------------------------------------------------------------------------
#include source code
INCS_DIRS += src/app/utils/jsonHelper/common \
			 src/app/dataManager
#-----------------------------------------------------------------------------
#
include ../Makefile

#-----------------------------------------------------------------------------