#modified IP
MESSAGE_RECEIVER_IP = "192.168.0.101"
MESSAGE_RECEIVER_PORT = 8787

ATTR_JSON_MESSAGE_TYPE = "MESSAGE_TYPE"
ATTR_JSON_MOBILE_STATUS_VALUE = "MOBILE_STATUS"
ATTR_JSON_ID_DEVICE = "ID_DEVICE"
ATTR_JSON_NAME_DEVICE = "NAME_DEVICE"
ATTR_JSON_RELAY_STATUS_VALUE = "RELAY_STATUS_VALUE"
ATTR_JSON_ELECTRIC_STATUS_VALUE = "ELECTRIC_STATUS_VALUE"
ATTR_JSON_RELAY_STATUS_VALUE_ACTIVE = 1
ATTR_JSON_RELAY_STATUS_VALUE_UNACTIVE = 0
ATTR_JSON_ID_ROOM = "ID_ROOM"
ATTR_JSON_DATA = "data"

ATTR_JSON_ID_SD001_VALUE = "SD001"
ATTR_JSON_ID_SD002_VALUE = "SD002"

ATTR_JSON_NAME_DEVICE_LIGHT_VALUE = "DEVICE_LIGHT"
ATTR_JSON_NAME_DEVICE_PLUS_VALUE = "DEVICE_PLUS"

ATTR_JSON_ID_ROOM_R001_VALUE = "R0001"
#end


HOST = 'localhost'
USER = 'root'
PASSWORD = 'root'
DATABASE = 'SMARTDEVICE'