MESSAGE_RECEIVER_IP = "192.168.0.100"
MESSAGE_RECEIVER_PORT = 8787

ATTR_JSON_MESSAGE_TYPE = "MESSAGE_TYPE"
ATTR_JSON_MOBILE_STATUS_VALUE = "MOBILE_STATUS"
ATTR_JSON_ID_DEVICE = "ID_DEVICE"
ATTR_JSON_NAME_DEVICE = "NAME_DEVICE"
ATTR_JSON_RELAY_STATUS_VALUE = "RELAY_STATUS_VALUE"
ATTR_JSON_ELECTRIC_STATUS_VALUE = "ELECTRIC_STATUS_VALUE"
ATTR_JSON_RELAY_STATUS_VALUE_ACTIVE = 1
ATTR_JSON_RELAY_STATUS_VALUE_UNACTIVE = 0
ATTR_JSON_ID_ROOM = "ID_ROOM"
ATTR_JSON_DATA = "data"

ATTR_JSON_ID_SD001_VALUE = "SD001"
ATTR_JSON_ID_SD002_VALUE = "SD002"

ATTR_JSON_NAME_DEVICE_LIGHT_VALUE = "DEVICE_LIGHT"
ATTR_JSON_NAME_DEVICE_PLUS_VALUE = "DEVICE_PLUS_"

ATTR_JSON_ID_ROOM_R001_VALUE = "R0001"

ATTR_JSON_MESSAGE_STATUS_VALUE_SELECT = "SELECT_DEVICE"

ATTR_JSON_MESSAGE_STATUS_VALUE_DEVICE = "ON_OFF_DEVICE"
ATTR_JSON_MESSAGE_STATUS_VALUE_LOGIN = "LOGIN_DEVICE"
ATTR_JSON_MESSAGE_STATUS_VALUE_REGISTER = "REGISTER_DEVICE"


# ATTR_JSON_USER_NAME = "USER_NAME"
# ATTR_JSON_PASSWORD = "PASSWORD"
# ATTR_JSON_EMAIL = "EMAIL"

ATTR_JSON_LOGIN_SUCCESSFUL_USER = "LOGIN_SUCCESSFUL_USER"
ATTR_JSON_LOGIN_SUCCESSFUL_ADMIN = "LOGIN_SUCCESSFUL_ADMIN"
ATTR_JSON_LOGIN_ERROR = "LOGIN_ERROR"
ATTR_JSON_LOGIN_ERROR_UNACTIVE = "LOGIN_ERROR_UNACTIVE"

ATTR_JSON_REGISTER_SUCCESSFUL = "REGISTER_SUCCESSFUL"
ATTR_JSON_REGISTER_EMAIL_EXIST = "EMAIL_EXIST"
ATTR_JSON_REGISTER_USERNAME_EXIST = "USERNAME_EXIST"
ATTR_JSON_REGISTER_ERROR = "REGISTER_ERROR"

ATTR_JSON_MESSAGE_STATUS_VALUE_SELECT_LIST_USERS = "SELECT_LIST_USERS";
ATTR_JSON_USER_NAME_IN_USERS = "USER_NAME"
ATTR_JSON_EMAIL_IN_USERS = "EMAIL"
ATTR_JSON_STATE_USER_IN_USERS = "STATE_USER"
ATTR_JSON_USER_STYLE_IN_USERS = "USER_STYLE"

ATTR_JSON_UPDATE_SUCCESSFUL_STATE_USER = "UPDATE_SUCCESSFUL_STATE_USER"
ATTR_JSON_UPDATE_ERROR_STATE_USER = "UPDATE_ERROR_STATE_USER"

ATTR_JSON_UPDATE_SUCCESSFUL_USER_STYLE = "UPDATE_SUCCESSFUL_USER_STYLE"
ATTR_JSON_UPDATE_ERROR_USER_STYLE = "UPDATE_ERROR_USER_STYLE"

ATTR_JSON_STATUS_VALUE_SELECT_HISTORY = "SELECT_HISTORY"

ATTR_JSON_DELETE_STATUS_VALUE_USER_SUCCESSFUL = "DELETE_USER_SUCCESSFUL";
ATTR_JSON_DELETE_STATUS_VALUE_USER_ERROR = "DELETE_USER_ERROR";

ATTR_JSON_MONTHSD = "MONTHSD"
ATTR_JSON_DAYSD = "DAYSD"
ATTR_JSON_YEARSD = "YEARSD"
ATTR_JSON_HOURSD = "HOURSD"
ATTR_JSON_MINUTESD = "MINUTESD"
ATTR_JSON_SECONDSD = "SECONDSD"


HOST = 'localhost'
USER = 'root'
PASSWORD = 'root'
DATABASE = 'SMARTDEVICE'