#-----------------------------------------------------------------------------
# Makefile - src/app/utils/jsonHelper/cWrapper/jsonCommonWrapper
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
APP = unittest
TEST_OBJECT = src/app/utils/jsonHelper/cWrapper/jsonCommonWrapper/jsonCommonWrapper_smart_device_status_value

#-----------------------------------------------------------------------------
LIBDIRS_jsonCommon  += $(LIDT_ROOT)/src/app/utils/jsonHelper/commonjsonCommon_smart_device_status_value/
LIBRARY             += jsonCommon_smart_device_status_value

#-----------------------------------------------------------------------------
#include source code
INCS_DIRS += src/app/utils/jsonHelper/common/jsonCommon_smart_device_status_value \
			 src/app/dataManager
#-----------------------------------------------------------------------------
#
include ../Makefile

#-----------------------------------------------------------------------------